# Camera and display settings
CAMERA_INDEX = 0
FRAME_WIDTH = 1280
FRAME_HEIGHT = 720
WINDOW_NAME = "Pose Joints Detector"

# MediaPipe Pose settings
POSE_MODEL_COMPLEXITY = 1
POSE_SMOOTH_LANDMARKS = True
POSE_MIN_DETECTION_CONFIDENCE = 0.5
POSE_MIN_TRACKING_CONFIDENCE = 0.5
